### ISSUE TITLE
Should be a port of modified asciidoc

### ISSUE THREAD

**Issue by bsdimp** [sergio-carlavilla/documentation-project-primer#3]
You should work with the ports team to get a modified asciidoc port to install for doc work. Having to redo the hack for hugo each time is going to lead to many tears.

**Comment by sergio-carlavilla** [comment]
Yes, I'm working with apesteguia@ to have a custom port of Hugo.
There's also a pull request in Hugo https://github.com/gohugoio/hugo/pull/8131/files

**Comment by sergio-carlavilla** [comment]
Fixed: https://svnweb.freebsd.org/ports?view=revision&revision=562416
I removed from the documentation this part.
