### ISSUE TITLE
How to convert po translations to new format?

### ISSUE THREAD

**Issue by ghost** [sergio-carlavilla/documentation-project-primer#4]
I have translated some part of handbook to Simplified Chinese. But not submitted to upstream. Translation can fetch from https://translate-dev.freebsd.org/projects/freebsd-doc/boooks_handbook/zh_CN/ 

The Chinese translation in the repository has not been updated for a long time.

I want to know how to convert po translations to new format.

**Comment by sergio-carlavilla** [comment]
Hi,
Don’t worry about that. We’re going to update the weblate instance to use AsciiDoc. You’re no gonna lose your work :)

bye
